### ISSUE TITLE
Publish it using GitHub Page

### ISSUE THREAD

**Issue by iROCKBUNNY** [UPITTINTROGROUP2/Orientation#1]
See: http://github.io/

**Comment by wanpiqiao** [comment]
You mean I should use Github for Mac? I cannot get your meaning.

**Comment by iROCKBUNNY** [comment]
If you want to publish this website so that people can have access to it through Internet, you should follow the steps offered by the following link: http://github.io/

Or, at least, add a new branch called: gh-pages
Hence you can visit your site via: http://UPITTINTROGROUP2.github.io/Orientation
